const theme = {
    light: {
        theme: 'light',
        bg: '#FFFFFF',
        background: '#4263EB',
        txt: '#000000',
        btn2: '#F9F9FA',
        bord: '#E3E7F7',
        input: '#F9F9FA',
        bgsplash: require('../../assets/image/Splash.png'),
        verify: require('../../assets/image/verify.png'),
        selfie: require('../../assets/image/Upload.png'),
        upload: require('../../assets/image/Uploadlight.png'),
        camera: require('../../assets/image/cameralight.png'),
        primary: '#F9F9FA',
        his: '#4263EB',
        fingerbg: require('../../assets/image/fingerbg.png'),
        img1: require('../../assets/image/Icon.png'),
        img2: require('../../assets/image/Icon2.png'),
        img3: require('../../assets/image/Icon1.png'),
        serviceImg1: require('../../assets/image/ganti-oli.png'),
        serviceImg2: require('../../assets/image/pertamini.png'),
        serviceImg3: require('../../assets/image/service-motor.png'),
        serviceImg4: require('../../assets/image/sparepart.jpg'),
        
        apple: require('../../assets/image/applestore.png'),
        iiya: require('../../assets/image/iiya.png'),
        btn: '#F5F7FE',
        back:'#FFFFFF',
        pin:require('../../assets/image/Pin.png'),
        message:require('../../assets/image/message.png'),
        chart:require('../../assets/image/Chart.png'),
        chart1:require('../../assets/image/Chart1.png'),
        card4:require('../../assets/image/card4.png'),

        // intro:require('../../assets/image/Intro1w.png'),
        // intro2:require('../../assets/image/Intro2w.png'),


    },
    dark: {
        theme: 'dark',
        bg: '#171725',
        background: '#000000',
        txt: '#FFFFFF',
        btn2: '#52525C',
        bord: '#52525C',
        input: '#211F32',
        // barstyle:'light-content',
        bgsplash: require('../../assets/image/Splash2.png'),
        verify: require('../../assets/image/verify2.png'),
        selfie: require('../../assets/image/Upload2.png'),
        upload: require('../../assets/image/Uploaddark.png'),
        camera: require('../../assets/image/cameradark.png'),
        primary: '#211F32',
        his: '#FFFFFF',
        fingerbg: require('../../assets/image/fingerbgdark.png'),
        img1: require('../../assets/image/Icondark.png'),
        img2: require('../../assets/image/Icon2dark.png'),
        img3: require('../../assets/image/Icon1dark.png'),
        apple: require('../../assets/image/applestoredark.png'),
        iiya: require('../../assets/image/iiyadark.png'),
        btn: '#323045',
        back:'#211F32',
        pin:require('../../assets/image/Pindark.png'),
        message:require('../../assets/image/messagedark.png'),
        chart:require('../../assets/image/Chartdark.png'),
        chart1:require('../../assets/image/Chart1dark.png'),
        card4:require('../../assets/image/card4dark.png'),

        // intro:require('../../assets/image/Intro1b.png'),
        // intro2:require('../../assets/image/Intro2b.png'),

    },

};

export default theme;